T = readtable('airlinesmall.csv', 'TreatAsMissing', 'NA') % reading the airlinesmall csv dataset and treat 'NA' as missing (in demos folder of your matlab installation)
%
% T =
%
%   123523×29 table
%
%     Year    Month    DayofMonth    DayOfWeek    DepTime    CRSDepTime    ArrTime    CRSArrTime    UniqueCarrier    FlightNum    TailNum    ActualElapsedTime    CRSElapsedTime    AirTime    ArrDelay    DepDelay    Origin      Dest      Distance    TaxiIn    TaxiOut    Cancelled    CancellationCode    Diverted    CarrierDelay    WeatherDelay    NASDelay    SecurityDelay    LateAircraftDelay
%     ____    _____    __________    _________    _______    __________    _______    __________    _____________    _________    _______    _________________    ______________    _______    ________    ________    _______    _______    ________    ______    _______    _________    ________________    ________    ____________    ____________    ________    _____________    _________________
%
%     1987     10          21            3          642          630         735          727          {'PS'}          1503         NaN              53                 57            NaN          8          12       {'LAX'}    {'SJC'}       308       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN
%     1987     10          26            1         1021         1020        1124         1116          {'PS'}          1550         NaN              63                 56            NaN          8           1       {'SJC'}    {'BUR'}       296       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN
%     1987     10          23            5         2055         2035        2218         2157          {'PS'}          1589         NaN              83                 82            NaN         21          20       {'SAN'}    {'SMF'}       480       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN
%     1987     10          23            5         1332         1320        1431         1418          {'PS'}          1655         NaN              59                 58            NaN         13          12       {'BUR'}    {'SJC'}       296       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN
%     1987     10          22            4          629          630         746          742          {'PS'}          1702         NaN              77                 72            NaN          4          -1       {'SMF'}    {'LAX'}       373       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN
%     1987     10          28            3         1446         1343        1547         1448          {'PS'}          1729         NaN              61                 65            NaN         59          63       {'LAX'}    {'SJC'}       308       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN
%     1987     10           8            4          928          930        1052         1049          {'PS'}          1763         NaN              84                 79            NaN          3          -2       {'SAN'}    {'SFO'}       447       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN
%     1987     10          10            6          859          900        1134         1123          {'PS'}          1800         NaN             155                143            NaN         11          -1       {'SEA'}    {'LAX'}       954       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN
%     1987     10          20            2         1833         1830        1929         1926          {'PS'}          1831         NaN              56                 56            NaN          3           3       {'LAX'}    {'SJC'}       308       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN
% ...
