T_joined = join(T_filt, T_agg, "Keys", ["Year", "Month"], "RightVariables", "mean_ArrDelay") % joining the aggregated values "mean_ArrDelay" of the right dataset T_agg on the keys "Year" and "Month". Keys must be named the same in both datasets.

% T_joined =
%
%   255×30 table
%
%     Year    Month    DayofMonth    DayOfWeek    DepTime    CRSDepTime    ArrTime    CRSArrTime    UniqueCarrier    FlightNum    TailNum    ActualElapsedTime    CRSElapsedTime    AirTime    ArrDelay    DepDelay    Origin      Dest      Distance    TaxiIn    TaxiOut    Cancelled    CancellationCode    Diverted    CarrierDelay    WeatherDelay    NASDelay    SecurityDelay    LateAircraftDelay    mean_ArrDelay
%     ____    _____    __________    _________    _______    __________    _______    __________    _____________    _________    _______    _________________    ______________    _______    ________    ________    _______    _______    ________    ______    _______    _________    ________________    ________    ____________    ____________    ________    _____________    _________________    _____________
%
%     1987     10          11            7         2300         2057        2246         2041          {'EA'}          1644         NaN              46                 44            NaN        125         123       {'ATL'}    {'HSV'}       151       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               5.8108
%     1987     11          26            4         1610         1320        2142         1836          {'CO'}           586         NaN             212                196            NaN        186         170       {'DEN'}    {'IAD'}      1452       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               7.5311
%     1987     12          23            3          345         2145         645          106          {'CO'}          1770         NaN             120                141            NaN        339         360       {'DEN'}    {'STL'}       770       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN                11.97
%     1988      1          13            3         1130         1000        1315         1107          {'CO'}           306         NaN             105                 67            NaN        128          90       {'DCA'}    {'EWR'}       199       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               11.053
%     1988      2          11            4         2158         1745          57         2040          {'UA'}           400         NaN             119                115            NaN        257         253       {'ORD'}    {'BTV'}       763       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               8.2138
%     1988      3          11            5          905         2000        1102         2210          {'PI'}           724         NaN              57                 70            NaN        772         785       {'ORD'}    {'LEX'}       323       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               10.014
%     1988      4          13            3         2012         1755        2213         2007          {'UA'}           762         NaN              61                 72            NaN        126         137       {'ORD'}    {'SDF'}       286       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               5.8892
%     1988      5           8            7          108         2125         144         2208          {'UA'}           880         NaN              36                 43            NaN        216         223       {'MHT'}    {'BGR'}       183       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN                5.963
%     1988      6          19            7         1947         1605        2124         1747          {'NW'}          1062         NaN              97                102            NaN        217         222       {'DTW'}    {'LGA'}       501       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               5.1729
%     1988      7          20            3         2324         1856         144         2123          {'PI'}           581         NaN             140                147            NaN        261         268       {'BWI'}    {'PBI'}       883       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               6.5492
%     1988      8          28            7          941          700        1056          800          {'AA'}           509         NaN              75                 60            NaN        176         161       {'BOS'}    {'JFK'}       187       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               5.6329
%     1988      9          22            4         2004         1730        2123         1849          {'AA'}           465         NaN              79                 79            NaN        154         154       {'SAN'}    {'SJC'}       417       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN                 2.87
%     1988     10           5            3         2039         1810        2313         2045          {'PI'}          1410         NaN              94                 95            NaN        148         149       {'ORD'}    {'GSO'}       590       NaN        NaN          0              NaN              0            NaN             NaN           NaN            NaN                NaN               4.0619
% ...